#controller_manager_ns: mico
controller_list:
 - name: /mico/mico_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - mico_joint_1
     - mico_joint_2
     - mico_joint_3
     - mico_joint_4
     - mico_joint_5
     - mico_joint_6
